export const materials = [
  {
    id: 'premium-portland-cement',
    name: 'Premium Portland Cement',
    category: 'Concrete',
    price: 14,
    unit: 'per 50kg bag',
    availability: 'In Stock',
    supplier: 'Accra Build Supply',
    stock: 420,
    delivery: 'Same-day dispatch',
    description:
      'High-strength Portland cement for foundations, block work, plastering, and general site use. Packed for reliable storage and consistent mixing.',
    gallery: ['Bag detail', 'Stacked pallets', 'Site mix view'],
  },
  {
    id: 'high-tensile-rebar-bundle',
    name: 'High-Tensile Rebar Bundle',
    category: 'Steel',
    price: 420,
    unit: 'per bundle',
    availability: 'In Stock',
    supplier: 'Tema Steel Works',
    stock: 86,
    delivery: 'Delivery in 2 days',
    description:
      'Grade-tested reinforcement bars bundled for structural concrete work, columns, beams, slabs, and other load-bearing applications.',
    gallery: ['Bundle overview', 'Ribbed bar detail', 'Warehouse stock'],
  },
  {
    id: 'ready-mix-concrete',
    name: 'Ready-Mix Concrete C25',
    category: 'Concrete',
    price: 135,
    unit: 'per cubic meter',
    availability: 'Preorder',
    supplier: 'Metro Concrete',
    stock: 32,
    delivery: 'Scheduled delivery',
    description:
      'Batch-controlled C25 ready-mix concrete prepared for slabs, driveways, and medium-duty structural works with scheduled truck delivery.',
    gallery: ['Mixer truck', 'Pour finish', 'Batch plant'],
  },
  {
    id: 'treated-timber-planks',
    name: 'Treated Timber Planks',
    category: 'Timber',
    price: 32,
    unit: 'per plank',
    availability: 'Low Stock',
    supplier: 'Kumasi Timber Yard',
    stock: 18,
    delivery: 'Delivery in 3 days',
    description:
      'Pressure-treated timber planks for framing, temporary works, roofing support, and durable outdoor construction applications.',
    gallery: ['Timber stack', 'Grain detail', 'Cut lengths'],
  },
  {
    id: 'ceramic-floor-tiles',
    name: 'Matte Ceramic Floor Tiles',
    category: 'Finishes',
    price: 28,
    unit: 'per box',
    availability: 'In Stock',
    supplier: 'Urban Finishings',
    stock: 140,
    delivery: 'Pickup available',
    description:
      'Durable matte ceramic floor tiles suitable for residential and commercial interiors with a clean modern finish.',
    gallery: ['Tile pattern', 'Surface finish', 'Room sample'],
  },
  {
    id: 'electrical-cable-roll',
    name: 'Copper Electrical Cable Roll',
    category: 'Electrical',
    price: 76,
    unit: 'per 100m roll',
    availability: 'In Stock',
    supplier: 'PowerLine Depot',
    stock: 64,
    delivery: 'Delivery in 24 hours',
    description:
      'Flexible copper electrical cable roll for site wiring, lighting circuits, and general electrical installation work.',
    gallery: ['Cable roll', 'Copper core', 'Label detail'],
  },
  {
    id: 'roofing-sheets',
    name: 'Aluzinc Roofing Sheets',
    category: 'Roofing',
    price: 58,
    unit: 'per sheet',
    availability: 'Low Stock',
    supplier: 'North Ridge Roofing',
    stock: 24,
    delivery: 'Delivery in 2 days',
    description:
      'Weather-resistant Aluzinc roofing sheets with a clean profile for residential, commercial, and light industrial roofing.',
    gallery: ['Sheet profile', 'Roof sample', 'Stacked sheets'],
  },
  {
    id: 'site-safety-kit',
    name: 'Complete Site Safety Kit',
    category: 'Safety',
    price: 89,
    unit: 'per kit',
    availability: 'In Stock',
    supplier: 'SafeBuild Ghana',
    stock: 52,
    delivery: 'Same-day dispatch',
    description:
      'Starter safety kit with essential personal protective equipment for construction crews, visitors, and site supervisors.',
    gallery: ['Full kit', 'Helmet and vest', 'Packed kit'],
  },
]

export const priceRanges = [
  { label: 'All prices', value: 'all' },
  { label: 'Under GH₵50', value: 'under-50', min: 0, max: 50 },
  { label: 'GH₵50 - GH₵150', value: '50-150', min: 50, max: 150 },
  { label: 'Over GH₵150', value: 'over-150', min: 150 },
]
