export const workers = [
  {
    id: 'daniel-mensah',
    name: 'Daniel Mensah',
    role: 'Masonry Specialist',
    profession: 'Mason',
    rating: 4.9,
    projects: '128 projects',
    location: 'Accra',
    availability: 'Available this week',
    rate: 'GH₵180/day',
    experience: '9 years',
    bio: 'Daniel leads blockwork, plastering, and concrete repair teams for residential and commercial projects across Greater Accra.',
    skills: ['Block laying', 'Concrete repair', 'Plastering', 'Site layout'],
    completedJobs: [
      '12-unit apartment block masonry',
      'Boundary wall and gatehouse build',
      'Retail shop plastering finish',
    ],
    reviews: [
      {
        id: 'daniel-site-manager',
        name: 'Nana Adjei',
        rating: 5,
        comment:
          'Daniel kept the masonry crew organized and delivered clean blockwork ahead of schedule.',
      },
      {
        id: 'daniel-developer',
        name: 'Esi Coleman',
        rating: 4.8,
        comment:
          'Reliable, careful with measurements, and easy to coordinate with our site supervisor.',
      },
    ],
  },
  {
    id: 'ama-owusu',
    name: 'Ama Owusu',
    role: 'Licensed Electrician',
    profession: 'Electrician',
    rating: 4.8,
    projects: '94 projects',
    location: 'Tema',
    availability: 'Available tomorrow',
    rate: 'GH₵220/day',
    experience: '7 years',
    bio: 'Ama handles wiring, panel upgrades, lighting layouts, and site power checks for new builds and renovations.',
    skills: ['Wiring', 'Panel installation', 'Lighting', 'Fault tracing'],
    completedJobs: [
      'Office lighting retrofit',
      'Three-bedroom house wiring',
      'Warehouse distribution board upgrade',
    ],
    reviews: [
      {
        id: 'ama-facility',
        name: 'Kojo Frimpong',
        rating: 4.9,
        comment:
          'Ama explained every electrical issue clearly and finished the panel work neatly.',
      },
      {
        id: 'ama-homeowner',
        name: 'Akosua Manu',
        rating: 4.7,
        comment: 'Professional, punctual, and very careful with safety checks.',
      },
    ],
  },
  {
    id: 'kwame-boateng',
    name: 'Kwame Boateng',
    role: 'Structural Welder',
    profession: 'Welder',
    rating: 4.9,
    projects: '112 projects',
    location: 'Kumasi',
    availability: 'Available this week',
    rate: 'GH₵240/day',
    experience: '11 years',
    bio: 'Kwame fabricates gates, roofing frames, stair rails, and structural steel connections for commercial sites.',
    skills: ['Arc welding', 'Steel fabrication', 'Gate works', 'Frame repairs'],
    completedJobs: [
      'Warehouse truss reinforcement',
      'Custom security gate installation',
      'Steel staircase fabrication',
    ],
    reviews: [
      {
        id: 'kwame-contractor',
        name: 'Yaw Bediako',
        rating: 5,
        comment:
          'Strong welding work and a very tidy finish on our steel staircase.',
      },
      {
        id: 'kwame-factory',
        name: 'Mariam Issah',
        rating: 4.8,
        comment:
          'He handled urgent frame repairs without disrupting our production floor.',
      },
    ],
  },
  {
    id: 'esi-coleman',
    name: 'Esi Coleman',
    role: 'Finishing Carpenter',
    profession: 'Carpenter',
    rating: 4.7,
    projects: '76 projects',
    location: 'Cape Coast',
    availability: 'Booked until Friday',
    rate: 'GH₵190/day',
    experience: '6 years',
    bio: 'Esi specializes in built-in storage, doors, trims, and detailed finish carpentry for residential interiors.',
    skills: ['Cabinetry', 'Door fitting', 'Trim work', 'Furniture repairs'],
    completedJobs: [
      'Kitchen cabinet installation',
      'Hotel room door replacement',
      'Custom wardrobe fit-out',
    ],
    reviews: [
      {
        id: 'esi-architect',
        name: 'Kofi Appiah',
        rating: 4.7,
        comment:
          'Esi brought patience and precision to a tricky custom wardrobe job.',
      },
      {
        id: 'esi-owner',
        name: 'Abena Sarpong',
        rating: 4.6,
        comment: 'Excellent finish quality and good communication throughout.',
      },
    ],
  },
  {
    id: 'yaw-antwi',
    name: 'Yaw Antwi',
    role: 'Roofing Installer',
    profession: 'Roofer',
    rating: 4.6,
    projects: '83 projects',
    location: 'Takoradi',
    availability: 'Available next week',
    rate: 'GH₵210/day',
    experience: '8 years',
    bio: 'Yaw installs Aluzinc sheets, gutters, fascia boards, and roof repairs for coastal and inland projects.',
    skills: ['Roof sheet installation', 'Gutters', 'Leak repairs', 'Fascia work'],
    completedJobs: [
      'Residential roofing replacement',
      'Warehouse gutter installation',
      'Storm damage leak repair',
    ],
    reviews: [
      {
        id: 'yaw-builder',
        name: 'Joseph Armah',
        rating: 4.6,
        comment:
          'Yaw handled our roofing replacement quickly before the rains came.',
      },
      {
        id: 'yaw-client',
        name: 'Maame Essel',
        rating: 4.5,
        comment: 'Good team coordination and very helpful with material checks.',
      },
    ],
  },
  {
    id: 'akua-serwaa',
    name: 'Akua Serwaa',
    role: 'Site Plumber',
    profession: 'Plumber',
    rating: 4.8,
    projects: '69 projects',
    location: 'Accra',
    availability: 'Available today',
    rate: 'GH₵200/day',
    experience: '5 years',
    bio: 'Akua supports water supply, drainage, fixture installation, and pressure testing for homes and small commercial builds.',
    skills: ['Pipe fitting', 'Drainage', 'Fixture installation', 'Leak testing'],
    completedJobs: [
      'Apartment bathroom rough-in',
      'Restaurant drainage repair',
      'Water tank connection setup',
    ],
    reviews: [
      {
        id: 'akua-manager',
        name: 'Selasi Mensah',
        rating: 4.8,
        comment:
          'Akua diagnosed our drainage issue quickly and left the site spotless.',
      },
      {
        id: 'akua-landlord',
        name: 'Eric Tetteh',
        rating: 4.7,
        comment:
          'Very responsive and careful with fixture installation in occupied units.',
      },
    ],
  },
  {
    id: 'kojo-addai',
    name: 'Kojo Addai',
    role: 'Heavy Equipment Operator',
    profession: 'Equipment Operator',
    rating: 4.5,
    projects: '58 projects',
    location: 'Tamale',
    availability: 'Available this week',
    rate: 'GH₵260/day',
    experience: '10 years',
    bio: 'Kojo operates loaders, compactors, and excavators for earthworks, site clearing, and road preparation.',
    skills: ['Excavator operation', 'Compaction', 'Site clearing', 'Grading'],
    completedJobs: [
      'Road base preparation',
      'Commercial site clearing',
      'Foundation excavation support',
    ],
    reviews: [
      {
        id: 'kojo-engineer',
        name: 'Ibrahim Yakubu',
        rating: 4.5,
        comment:
          'Kojo understands site levels well and works safely around other crews.',
      },
      {
        id: 'kojo-supervisor',
        name: 'Amina Fuseini',
        rating: 4.4,
        comment: 'Dependable operator for long grading shifts.',
      },
    ],
  },
  {
    id: 'abena-nyarko',
    name: 'Abena Nyarko',
    role: 'Interior Painter',
    profession: 'Painter',
    rating: 4.7,
    projects: '101 projects',
    location: 'Tema',
    availability: 'Available in 2 days',
    rate: 'GH₵160/day',
    experience: '6 years',
    bio: 'Abena delivers clean interior painting, surface preparation, and touch-up work for homes, offices, and retail spaces.',
    skills: ['Surface prep', 'Interior painting', 'Color matching', 'Touch-ups'],
    completedJobs: [
      'Office repainting project',
      'Retail feature wall finish',
      'Apartment turnover painting',
    ],
    reviews: [
      {
        id: 'abena-office',
        name: 'Linda Aidoo',
        rating: 4.8,
        comment:
          'Abena protected the floors properly and gave our office a sharp finish.',
      },
      {
        id: 'abena-agent',
        name: 'Patrick Osei',
        rating: 4.6,
        comment:
          'Fast apartment repaint with very good attention to edges and cleanup.',
      },
    ],
  },
]
