export const workers = [
  {
    id: 'daniel-mensah',
    name: 'Daniel Mensah',
    role: 'Masonry Specialist',
    profession: 'Mason',
    rating: 4.9,
    projects: '128 projects',
    location: 'Accra',
    availability: 'Available this week',
    rate: 'GH₵180/day',
  },
  {
    id: 'ama-owusu',
    name: 'Ama Owusu',
    role: 'Licensed Electrician',
    profession: 'Electrician',
    rating: 4.8,
    projects: '94 projects',
    location: 'Tema',
    availability: 'Available tomorrow',
    rate: 'GH₵220/day',
  },
  {
    id: 'kwame-boateng',
    name: 'Kwame Boateng',
    role: 'Structural Welder',
    profession: 'Welder',
    rating: 4.9,
    projects: '112 projects',
    location: 'Kumasi',
    availability: 'Available this week',
    rate: 'GH₵240/day',
  },
  {
    id: 'esi-coleman',
    name: 'Esi Coleman',
    role: 'Finishing Carpenter',
    profession: 'Carpenter',
    rating: 4.7,
    projects: '76 projects',
    location: 'Cape Coast',
    availability: 'Booked until Friday',
    rate: 'GH₵190/day',
  },
  {
    id: 'yaw-antwi',
    name: 'Yaw Antwi',
    role: 'Roofing Installer',
    profession: 'Roofer',
    rating: 4.6,
    projects: '83 projects',
    location: 'Takoradi',
    availability: 'Available next week',
    rate: 'GH₵210/day',
  },
  {
    id: 'akua-serwaa',
    name: 'Akua Serwaa',
    role: 'Site Plumber',
    profession: 'Plumber',
    rating: 4.8,
    projects: '69 projects',
    location: 'Accra',
    availability: 'Available today',
    rate: 'GH₵200/day',
  },
  {
    id: 'kojo-addai',
    name: 'Kojo Addai',
    role: 'Heavy Equipment Operator',
    profession: 'Equipment Operator',
    rating: 4.5,
    projects: '58 projects',
    location: 'Tamale',
    availability: 'Available this week',
    rate: 'GH₵260/day',
  },
  {
    id: 'abena-nyarko',
    name: 'Abena Nyarko',
    role: 'Interior Painter',
    profession: 'Painter',
    rating: 4.7,
    projects: '101 projects',
    location: 'Tema',
    availability: 'Available in 2 days',
    rate: 'GH₵160/day',
  },
]
